name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: makeiso
        run: |
          xorriso -as mkisofs -o aarikos.iso ../aarikos
      - uses: actions/upload-artifact@v2
        with:
          name: isofile
          path: aarikos.iso
